# Generated by Django 4.2.11 on 2026-04-30 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0060_alter_userachievement_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_reminders_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email-напоминания о незакрытых задачах",
                    ),
                ),
                (
                    "email_moderation_results",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email-уведомления о результатах модерации",
                    ),
                ),
                (
                    "email_verification_results",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email-уведомления о результатах верификации",
                    ),
                ),
                (
                    "email_certificate_ready",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email-уведомления о готовности сертификата",
                    ),
                ),
                (
                    "email_deadline_warnings",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email-уведомления о приближении дедлайнов",
                    ),
                ),
                (
                    "inapp_notifications_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Внутренние уведомления PROCOLLAB"
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки уведомлений пользователя",
                "verbose_name_plural": "Настройки уведомлений пользователей",
            },
        ),
    ]
