# Generated by Django 4.2.11 on 2026-04-30 22:15

from django.db import migrations


def create_preferences(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    UserNotificationPreferences = apps.get_model("users", "UserNotificationPreferences")
    preferences = [
        UserNotificationPreferences(user_id=user_id)
        for user_id in CustomUser.objects.values_list("id", flat=True)
    ]
    UserNotificationPreferences.objects.bulk_create(
        preferences,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0061_usernotificationpreferences"),
    ]

    operations = [
        migrations.RunPython(create_preferences, migrations.RunPython.noop),
    ]
