# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0018_data_migration_draft_to_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogram",
            name="participation_format",
            field=models.CharField(
                choices=[("individual", "Individual"), ("team", "Team")],
                default="team",
                help_text="Team-size rule for a project linked to this championship.",
                max_length=20,
                verbose_name="Participation format",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="project_team_min_size",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                null=True,
                verbose_name="Minimum project team size",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="project_team_max_size",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Maximum project team size",
            ),
        ),
    ]
