# Generated by Django 4.2.11 on 2026-05-09 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


DEFAULT_DOCUMENTS = [
    (
        "privacy_policy",
        "PROCOLLAB MVP privacy policy",
        "mvp-2026-05-09",
        "PROCOLLAB processes participant personal data for championship registration, participation, communication, project review, and operational support.",
    ),
    (
        "participant_consent",
        "PROCOLLAB MVP participant personal data consent",
        "mvp-2026-05-09",
        "I consent to PROCOLLAB processing my personal data for participation in the selected case championship.",
    ),
    (
        "participation_terms",
        "PROCOLLAB MVP championship participation terms",
        "mvp-2026-05-09",
        "The participant accepts the rules of the selected case championship and agrees to follow the published participation conditions.",
    ),
]


def seed_legal_documents(apps, schema_editor):
    LegalDocument = apps.get_model("partner_programs", "LegalDocument")
    for doc_type, title, version, content_html in DEFAULT_DOCUMENTS:
        if LegalDocument.objects.filter(type=doc_type, is_active=True).exists():
            continue
        LegalDocument.objects.create(
            type=doc_type,
            title=title,
            version=version,
            content_html=content_html,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner_programs', '0019_partnerprogram_participation_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('privacy_policy', 'Privacy policy'), ('participant_consent', 'Participant personal data consent'), ('participation_terms', 'Participation terms')], db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=64)),
                ('content_url', models.URLField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal document',
                'verbose_name_plural': 'Legal documents',
                'ordering': ('type', '-created_at', '-id'),
                'indexes': [models.Index(fields=['type', 'is_active'], name='partner_pro_type_61c03f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerProgramParticipantConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_document_version', models.CharField(max_length=64)),
                ('privacy_policy_version', models.CharField(max_length=64)),
                ('participation_terms_version', models.CharField(max_length=128)),
                ('consent_text_snapshot', models.TextField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_consents', to='partner_programs.partnerprogram')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_participant_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant championship consent',
                'verbose_name_plural': 'Participant championship consents',
                'indexes': [models.Index(fields=['program', 'user'], name='partner_pro_program_97a6d1_idx'), models.Index(fields=['accepted_at'], name='partner_pro_accepte_83e3ab_idx')],
            },
        ),
        migrations.RunPython(seed_legal_documents, migrations.RunPython.noop),
    ]
