# Generated by Django 4.2.11 on 2026-05-09 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0007_auto_20230929_1727'),
        ('projects', '0032_hide_program_projects'),
        ('partner_programs', '0020_privacy_legal_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprogram',
            name='verification_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, default='not_requested', max_length=20, verbose_name='Verification status'),
        ),
        migrations.CreateModel(
            name='PartnerProgramVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('inn', models.CharField(blank=True, db_index=True, max_length=12)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('ogrn', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('contact_full_name', models.CharField(max_length=255)),
                ('contact_position', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=64)),
                ('company_role_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('company_not_confirmed', 'Company data is not confirmed'), ('insufficient_documents', 'Documents are insufficient'), ('invalid_documents', 'Documents are invalid'), ('contact_not_verified', 'Contact person is not verified'), ('other', 'Other reason')], max_length=40)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_verification_requests', to='projects.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_program_verification_requests', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='program_verification_requests', to='files.userfile')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_verification_requests', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='partner_programs.partnerprogram')),
            ],
            options={
                'verbose_name': 'Partner program verification request',
                'verbose_name_plural': 'Partner program verification requests',
                'ordering': ['-submitted_at', '-id'],
                'indexes': [models.Index(fields=['program', '-submitted_at'], name='partner_pro_program_93f7b0_idx'), models.Index(fields=['status', '-submitted_at'], name='partner_pro_status_3d230a_idx')],
            },
        ),
    ]
