# Generated by Django 4.2.11 on 2026-05-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import partner_programs.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partner_programs", "0021_partnerprogram_verification_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogram",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="Доступ только по приглашению",
                verbose_name="Закрытый чемпионат",
            ),
        ),
        migrations.CreateModel(
            name="PartnerProgramInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает использования"),
                            ("used", "Использовано"),
                            ("expired", "Истёк срок"),
                            ("revoked", "Отозвано"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        default=partner_programs.models.default_invite_expires_at,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_program_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_program_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="partner_programs.partnerprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приглашение в чемпионат",
                "verbose_name_plural": "Приглашения в чемпионаты",
                "ordering": ["-datetime_created", "-id"],
                "indexes": [
                    models.Index(
                        fields=["program", "status"],
                        name="partner_pro_program_45ac80_idx",
                    ),
                    models.Index(
                        fields=["program", "-datetime_created"],
                        name="partner_pro_program_8e0dca_idx",
                    ),
                ],
            },
        ),
    ]
