# Generated by Django 4.2.11 on 2026-05-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0022_partnerprogram_invites"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogram",
            name="frozen_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Frozen at"),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="readiness",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Readiness checklist"
            ),
        ),
        migrations.AlterField(
            model_name="partnerprogram",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_moderation", "Pending moderation"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                    ("frozen", "Frozen"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Program status",
            ),
        ),
    ]
