# Generated by Django 4.2.11 on 2026-05-09 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0007_auto_20230929_1727'),
        ('partner_programs', '0023_program_workflow_readiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='type',
            field=models.CharField(choices=[('privacy_policy', 'Privacy policy'), ('participant_consent', 'Participant personal data consent'), ('participation_terms', 'Participation terms'), ('organizer_terms', 'Organizer terms')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='PartnerProgramLegalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_rules_link', models.URLField(blank=True)),
                ('additional_terms_text', models.TextField(blank=True)),
                ('organizer_terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('organizer_terms_version', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer_terms_accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_program_organizer_terms', to=settings.AUTH_USER_MODEL)),
                ('participation_rules_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_legal_rule_settings', to='files.userfile')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_settings', to='partner_programs.partnerprogram')),
            ],
            options={
                'verbose_name': 'Program legal settings',
                'verbose_name_plural': 'Program legal settings',
            },
        ),
        migrations.CreateModel(
            name='PersonalDataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('participant_list_view', 'Participant list view'), ('participant_contact_view', 'Participant contact view'), ('participant_export_download', 'Participant export download')], max_length=64)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_data_access_logs', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data_access_logs', to='partner_programs.partnerprogram')),
            ],
            options={
                'verbose_name': 'Personal data access log',
                'verbose_name_plural': 'Personal data access logs',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['program', 'action', 'created_at'], name='partner_pro_program_41d9ca_idx'), models.Index(fields=['actor', 'created_at'], name='partner_pro_actor_i_b0da55_idx')],
            },
        ),
    ]
