from django.urls import path

from certificates.views import (
    CertificateFontListView,
    IssuedCertificateDeleteView,
    MyProgramCertificateView,
    ProgramCertificateDownloadView,
    ProgramCertificateGenerationStartView,
    ProgramCertificateGenerationStatsView,
    ProgramCertificateLegacyTemplateView,
    ProgramCertificateListView,
    ProgramCertificatePreviewPdfView,
    ProgramCertificateReleaseView,
    ProgramCertificateTemplatePreviewView,
    ProgramCertificateTemplateView,
    PublicCertificateVerificationAPIView,
    PublicCertificateVerificationPageView,
)

app_name = "certificates"

urlpatterns = [
    path(
        "programs/<int:pk>/certificate/settings/",
        ProgramCertificateTemplateView.as_view(),
        name="program-certificate-settings",
    ),
    path(
        "programs/<int:pk>/certificate/preview/",
        ProgramCertificatePreviewPdfView.as_view(),
        name="program-certificate-preview",
    ),
    path(
        "programs/<int:pk>/certificate/generate/",
        ProgramCertificateGenerationStartView.as_view(),
        name="program-certificate-generate",
    ),
    path(
        "programs/<int:pk>/certificate/release/",
        ProgramCertificateReleaseView.as_view(),
        name="program-certificate-release",
    ),
    path(
        "programs/<int:pk>/certificate/list/",
        ProgramCertificateListView.as_view(),
        name="program-certificate-list",
    ),
    path(
        "programs/<int:pk>/certificate/me/",
        MyProgramCertificateView.as_view(),
        name="program-certificate-me",
    ),
    path(
        "programs/<int:pk>/certificate/<str:certificate_id>/download/",
        ProgramCertificateDownloadView.as_view(),
        name="program-certificate-download",
    ),
    path(
        "programs/<int:pk>/certificate-template/",
        ProgramCertificateLegacyTemplateView.as_view(),
        name="program-certificate-template",
    ),
    path(
        "programs/<int:pk>/certificate-template/preview/",
        ProgramCertificateTemplatePreviewView.as_view(),
        name="program-certificate-template-preview",
    ),
    path(
        "programs/<int:pk>/certificate-template/stats/",
        ProgramCertificateGenerationStatsView.as_view(),
        name="program-certificate-template-stats",
    ),
    path(
        "programs/<int:pk>/certificates/generate/",
        ProgramCertificateGenerationStartView.as_view(),
        name="program-certificate-generation-start",
    ),
    path(
        "programs/<int:pk>/my-certificate/",
        MyProgramCertificateView.as_view(),
        name="my-program-certificate",
    ),
    path(
        "api/partner-programs/<int:pk>/my-certificate/",
        MyProgramCertificateView.as_view(),
        name="api-my-program-certificate",
    ),
    path(
        "api/admin/certificates/<int:pk>/",
        IssuedCertificateDeleteView.as_view(),
        name="admin-issued-certificate-delete",
    ),
    path(
        "api/public/certificates/verify/<str:certificate_uuid>/",
        PublicCertificateVerificationAPIView.as_view(),
        name="api-public-certificate-verify",
    ),
    path(
        "certificates/verify/<str:certificate_uuid>/",
        PublicCertificateVerificationPageView.as_view(),
        name="public-certificate-verify",
    ),
    path(
        "api/certificates/fonts/",
        CertificateFontListView.as_view(),
        name="certificate-fonts",
    ),
]
