# Generated by Django 4.2.11 on 2026-05-01 14:59

import certificates.enums
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partner_programs", "0021_partnerprogram_verification_status_and_more"),
        ("files", "0007_auto_20230929_1727"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramCertificateTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        choices=[
                            ("roboto", "Roboto"),
                            ("open_sans", "Open Sans"),
                            ("pt_sans", "PT Sans"),
                            ("montserrat", "Montserrat"),
                            ("manrope", "Manrope"),
                            ("inter", "Inter"),
                        ],
                        default="roboto",
                        max_length=32,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        default="#1A1A1A",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a HEX value in #RRGGBB format.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "accent_text_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Color must be a HEX value in #RRGGBB format.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "fields_positioning",
                    models.JSONField(
                        blank=True,
                        default=certificates.enums.get_default_fields_positioning,
                    ),
                ),
                (
                    "issue_condition_type",
                    models.CharField(
                        choices=[
                            ("all_registered", "All registered participants"),
                            ("submitted_project", "Participants with submitted projects"),
                            (
                                "score_threshold",
                                "Participants with score above threshold",
                            ),
                            ("top_positions", "Prize positions"),
                        ],
                        default="all_registered",
                        max_length=32,
                    ),
                ),
                (
                    "min_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("top_positions", models.PositiveIntegerField(blank=True, null=True)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate_templates",
                        to="files.userfile",
                    ),
                ),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_template",
                        to="partner_programs.partnerprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program certificate template",
                "verbose_name_plural": "Program certificate templates",
                "ordering": ["-datetime_updated", "-id"],
            },
        ),
    ]
