# Generated by Django 4.2.11 on 2026-05-01 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_auto_20230929_1727"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partner_programs", "0021_partnerprogram_verification_status_and_more"),
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateGenerationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("total_expected", models.PositiveIntegerField(default=0)),
                ("enqueued_count", models.PositiveIntegerField(default=0)),
                ("issued_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_generation_runs",
                        to="partner_programs.partnerprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate generation run",
                "verbose_name_plural": "Certificate generation runs",
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IssuedCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=255)),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("rating_position", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "certificate_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "pdf_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_certificates",
                        to="files.userfile",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_certificates",
                        to="partner_programs.partnerprogram",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issued certificate",
                "verbose_name_plural": "Issued certificates",
                "ordering": ["-issued_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["program", "user"], name="certificate_program_70a5d9_idx"
                    ),
                    models.Index(
                        fields=["certificate_uuid"], name="certificate_certifi_a158ae_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="issuedcertificate",
            constraint=models.UniqueConstraint(
                fields=("program", "user"), name="uniq_issued_certificate_program_user"
            ),
        ),
        migrations.AddIndex(
            model_name="certificategenerationrun",
            index=models.Index(
                fields=["program", "-started_at"], name="certificate_program_d46f6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificategenerationrun",
            index=models.Index(
                fields=["status", "-started_at"], name="certificate_status_42f385_idx"
            ),
        ),
    ]
