# Generated by Django 4.2.11 on 2026-05-09 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner_programs', '0020_privacy_legal_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('verification_submitted', 'Verification submitted'), ('verification_approve', 'Verification approve'), ('verification_reject', 'Verification reject'), ('verification_revoke', 'Verification revoke')], db_index=True, max_length=40)),
                ('status_before', models.CharField(blank=True, max_length=20)),
                ('status_after', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=40)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='partner_programs.partnerprogram')),
            ],
            options={
                'verbose_name': 'Moderation log',
                'verbose_name_plural': 'Moderation logs',
                'ordering': ['-datetime_created', '-id'],
                'indexes': [models.Index(fields=['program', 'action', '-datetime_created'], name='moderation__program_7dee7a_idx')],
            },
        ),
    ]
