# Generated by Django 4.2.11 on 2026-05-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationlog",
            name="sections_to_fix",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="moderationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("submit_to_moderation", "Submit to moderation"),
                    ("submitted", "Submit to moderation"),
                    ("approve", "Approve"),
                    ("approved", "Approve"),
                    ("reject", "Reject"),
                    ("rejected", "Reject"),
                    ("withdraw", "Withdraw"),
                    ("withdrawn", "Withdraw"),
                    ("auto_freeze", "Automatic freeze"),
                    ("freeze", "Manual freeze"),
                    ("restore", "Restore"),
                    ("archive", "Archive"),
                    ("complete", "Complete"),
                    ("verification_submitted", "Verification submitted"),
                    ("verification_approve", "Verification approve"),
                    ("verification_reject", "Verification reject"),
                    ("verification_revoke", "Verification revoke"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
