# Generated by Django 4.2.11 on 2026-05-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_program_workflow_readiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('insufficient_data', 'Insufficient data'), ('platform_rules', 'Platform rules violation'), ('duplicate', 'Duplicate championship'), ('inappropriate_content', 'Inappropriate content'), ('suspicious_organizer', 'Suspicious organizer'), ('other', 'Other reason')], max_length=40),
        ),
    ]
