# Generated by Django 4.2.11 on 2026-05-09 17:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner_programs', '0021_partnerprogram_verification_status_and_more'),
        ('project_rates', '0003_projectexpertassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], db_index=True, default='draft', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('program_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='partner_programs.partnerprogramproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project evaluation',
                'verbose_name_plural': 'Project evaluations',
            },
        ),
        migrations.AddField(
            model_name='criteria',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Criterion weight, %'),
        ),
        migrations.CreateModel(
            name='ProjectEvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_scores', to='project_rates.criteria')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_scores', to='project_rates.projectevaluation')),
            ],
            options={
                'verbose_name': 'Project evaluation score',
                'verbose_name_plural': 'Project evaluation scores',
                'indexes': [models.Index(fields=['evaluation', 'criterion'], name='project_rat_evaluat_f5df48_idx')],
                'unique_together': {('evaluation', 'criterion')},
            },
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['program_project', 'user'], name='project_rat_program_445ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['status'], name='project_rat_status_005abb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectevaluation',
            unique_together={('program_project', 'user')},
        ),
    ]
